###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

normal[:mod_php5_apache2][:packages] = [ 'php56-common',
                                         'php56-cli',
                                         'php56-curl',
                                         'php56-gd',
                                         'php56-intl',
                                         'php56-mcrypt',
                                         'php56-memcache',
                                         'php56-imap',
                                         'php56-mysql',
                                         'php56-mongo']